spring.application.name=sistema-de-gestao
# definir a porta onde o servidor vai esta conectada
server.port=8081
spring.datasource.url = jdbc:postgresql://localhost:5433/sgace_database
spring.datasource.username = postgres
spring.datasource.password = tigre2017